name: Docker Compose CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  docker-compose-test:

    runs-on: docker-runner

    env:
      GITHUB_OWNER: ${{ vars.GH_OWNER }}
      GITHUB_REPO: ${{ vars.GH_REPO }}
      GITHUB_TOKEN: ${{ secrets.GH_PAT }}

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build and Start Containers
        run: docker compose up --build -d

      - name: Wait for Application Startup
        run: sleep 20

      - name: Check Running Containers
        run: docker ps

      - name: Verify GitHub Environment Variables
        run: |
          docker exec cicd-app printenv | grep GITHUB

      - name: Test Health Endpoint
        run: curl http://localhost:5000/health

      - name: Test GitHub Configuration Endpoint
        run: curl http://localhost:5000/github-config

      - name: Show Application Logs
        if: always()
        run: docker logs cicd-app

      - name: Stop Containers
        if: always()
        run: docker compose down
