name: Docker Compose CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  docker-compose-test:

    runs-on:
      - self-hosted
      - docker-runner

    env:
      GITHUB_OWNER: ${{ vars.GH_OWNER }}
      GITHUB_REPO: ${{ vars.GH_REPO }}
      GITHUB_TOKEN: ${{ secrets.GH_PAT }}

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build and Start Containers
        run: docker compose up --build -d

      - name: Wait for Application Startup
        shell: powershell
        run: Start-Sleep -Seconds 20

      - name: Check Running Containers
        run: docker ps -a

      - name: Show Environment Variables Inside Container
        run: docker exec cicd-app printenv

      - name: Verify Health Endpoint
        shell: powershell
        run: |
          $response = Invoke-RestMethod -Uri "http://localhost:5000/health"
          $response | ConvertTo-Json

      - name: Verify GitHub Configuration
        shell: powershell
        run: |
          $response = Invoke-RestMethod -Uri "http://localhost:5000/github-config"
          $response | ConvertTo-Json

      - name: Show Application Logs
        if: always()
        run: docker logs cicd-app

      - name: Show Database Logs
        if: always()
        run: docker logs postgres-db

      # Uncomment after debugging
      # - name: Stop Containers
      #   if: always()
      #   run: docker compose down
